content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
media:
  input: assets/img
  output: _site/assets/img
  