content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, categories, tags ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: categories
        label: Categories
        type: collection
      - name: tags
        label: Tags
        type: collection
      - name: body
        label: Body
        type: rich-text
      - name: image
        label: Image
        type: image
        list: true
        options:
          path: assets/img
          extensions: [ jpg, jpeg, png ]
media: _site/assets/img