content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, categories, tags ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: categories
        label: Categories
        type: collection
      - name: tags
        label: Tags
        type: collection
      - name: body
        label: Body
        type: rich-text
      - name: layout
        label: Layout
        type: string
      - name: image
        label: Image
        type: image
        list: true
        options:
          path: assets/img
          extensions: [ jpg, jpeg, png ]
  - name: thoughts
    label: Thoughts
    type: collection
    path: '_thoughts'
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date 
      - name: layout
        label: Layout
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: image
        label: Image
        type: image
        list: true
        options:
          path: assets/img
          extensions: [ jpg, jpeg, png ]
media: assets/img